version = 1

[[annotations]]
path = [
    ".github/FUNDING.yml",
    ".github/dependabot.yml",
    ".github/workflows/ci.yml",
    ".github/workflows/release.yml",
    ".gitignore",
    ".env",
    "REUSE.toml",
    "README.md",
    "Cargo.toml",
    "examples/.env",
    "examples/*.rs",
    "docker-compose.yaml",
    "rustfmt.toml",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2020 J0rsa and contributors"
SPDX-License-Identifier = "MIT"
